spring:
  application:
    name: saga-orchestrator

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: saga-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: com.deepana.saga.commondto

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual
      missing-topics-fatal: false


server:
  port: 8084   # Any free port


logging:
  level:
    root: INFO
    com.deepana: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info
